export const SNIPPETS = [
  {
    id: 1,
    title: 'Ganesh',
    description: 'Ganesh',
    liveurl: '/ganesh',
    source: '',
    image: '',
  },
  {
    id: 2,
    title: 'Hanuman',
    description: 'Hanuman',
    liveurl: '/hanuman',
    source: '',
    image: '',
  },
  {
    id: 3,
    title: 'Ram',
    description: 'Ram',
    liveurl: '/ram',
    source: '',
    image: '',
  },
  {
    id: 4,
    title: 'krishna',
    description: 'krishna',
    liveurl: '/krishna',
    source: '',
    image: '',
  },
  {
    id: 5,
    title: 'lakshmi',
    description: 'lakshmi',
    liveurl: './lakshmi',
    source: '',
    image: '',
  },
  {
    id: 6,
    title: 'demo',
    description: 'description',
    liveurl: '',
    source: '',
    image: '',
  },
  {
    id: 7,
    title: 'demo',
    description: 'description',
    liveurl: '',
    source: '',
    image: '',
  },
];
